URL_SERVICE = "https://13f7c205-7074-4700-9ad1-f5d29d969c94.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_KIT_PATH = "/api/v1/kits/"